name = "rdap-lookup-client"
type = "webpack"
route = 'lookup.cyberjake.xyz/*'
zone_id = ''
usage_model = ''
account_id = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./dist",entry-point = "workers-site"}
compatibility_date = "2022-03-12"
