name: Build Angular

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/*'
      - '.github/workflows/main.yml'
      - 'package.json'
    tags:
      - "v*"
  pull_request:
    branches: [main]
    paths: ['package.json']


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: npm install 
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci
      
      - name: Build
        run: npm run build

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}